FROM mysql:5.7.26

# Add Maintainer Info
LABEL maintainer=mogikanensoftware@gmail.com

# Set root pwd
ENV MYSQL_ROOT_PASSWORD Welcome1

# Add database
ENV MYSQL_DATABASE db_people

# Add username and pwd
ENV MYSQL_USER mytest
ENV MYSQL_PASSWORD Welcome2

EXPOSE 3306
